### ISSUE TITLE
Couple of suggestions "Anton Zharikov"

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [wishihab/steamscamsite#1]
![image](https://user-images.githubusercontent.com/13170204/49220378-5c2ffd80-f3d6-11e8-8d9a-ba1aadb703ae.png)
https://www.scamadviser.com/check-website/tf2pounce.com

tf2winner.com
  [Russian Federation] ru
tf2dragon.com
  [Russian Federation] ru
tf2sweet.com
  [Russian Federation] ru
tf2forest.com
  [Russian Federation] ru
tf2smart.com
  [Russian Federation] ru
tf2red.com
  [Russian Federation] ru
tf2effect.com
  [Russian Federation] ru
tf2bunch.com
  [Russian Federation] ru
tf2loaded.com
  [Russian Federation] ru
tf2dark.com
  [Russian Federation] ru
tf2euro.com
  [Russian Federation] ru

**Comment by PoorPocketsMcNewHold** [comment]
_(Oh, and forgot to ask since about [that domains filter list](https://github.com/PoorPocketsMcNewHold/steamscamsite), feel free to answer about what to which to do knowing that)_

**Comment by PoorPocketsMcNewHold** [comment]
![image](https://printscreen.party/k9cIm6uv.png)
[https://www.scamadviser.com/check-website/tf2violet.com](https://www.scamadviser.com/check-website/tf2violet.com)
Same server, with the same owner.
tf2violet.com tf2winner.com tf2dragon.com tf2sweet.com  tf2forest.com tf2smart.com tf2red.com  tf2effect.com  tf2bunch.com  tf2loaded.com  tf2dark.com

**Comment by Ojjjjjlol** [comment]
anton zharikov epic comeback XD
![image](https://user-images.githubusercontent.com/75545517/130442136-a02e3422-854c-4470-90f7-002863d5563f.png)
https://www.scamadviser.com/check-website/tf2sensation.com
