### ISSUE TITLE
Steam Workshop CS:GO Gambling website scam.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [wishihab/steamscamsite#2]
https://csgozfunny.com 
![image](https://user-images.githubusercontent.com/13170204/49669870-00631580-fa63-11e8-882f-6c6102eae2b9.png)
[](https://www.scamadviser.com/check-website/csgozfunny.com)

- Only have a couple days of existence.
- Is advertised by harsh spam.
- Hosted in Russia (Yeah, that's count for me)
- Others related domains of this one, are mostly pornographic or actual gambling website (Surely scam aswell for those too)

**Comment by PoorPocketsMcNewHold** [comment]
Forgot to add, It redirects to another domain strangely. 
https://cs-power.pw
Same thing, Only 5 days old, and is surely hosted in Russia, despite some effort of hiding that.
The registration address seems to be the same for the other domain, despite not being named for this one.
![image](https://user-images.githubusercontent.com/13170204/49670525-3ef9cf80-fa65-11e8-8f31-4844148aaef3.png)

**Comment by wishihab** [comment]
Thanks for the report issues
