### ISSUE TITLE
Fake CS:GO trading website with a fake logon window

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [wishihab/steamscamsite#3]
![image](https://cdn.discordapp.com/attachments/244901114850443266/525059254684483624/unknown.png)
![image](https://cdn.discordapp.com/attachments/244901114850443266/525060138722263051/unknown.png)
![image](https://cdn.discordapp.com/attachments/244901114850443266/525061013754871838/unknown.png)
![image](https://i.imgur.com/ES4UaR9.png)
![image](https://cdn.discordapp.com/attachments/244901114850443266/525062694424936458/unknown.png)
https://www.scamadviser.com/check-website/skinstats.net
skinstats.net 
This one domains however, seems to be linked to others gambling, pornographic and others kinds of shaddy website however from the same server.

**Comment by wishihab** [comment]
Thanks for the report issues!!
